### ISSUE TITLE
improve telescope module

### ISSUE THREAD

**Issue by paulthebaker** [PsrSigSim/VersionZeroPointZero#1]
We should have a generic telescope object that is defined by system temperature and collecting area.  Given a pulse in units of physical flux, it could generate appropriate radiometer noise to add to output voltages.

The telescope should also have (a dictionary of ?) receiver objects defined by observing frequency and bandwidth.  I imagine there is a non-flat frequency response function.

T<sub>sky</sub> depends on pointing altitude.  I need to remember my temperature definitions: T<sub>antenna</sub>, T<sub>receiver</sub>, T<sub>source</sub>, T<sub>sys</sub>, etc

We should have pre-initialized telescopes for GBT and AO containing their actual physical parameters and receivers (up to L-band?).  Bandwidth is a function of backend, if the backend can't capture all of the receiver's range?

**Comment by Hazboun6** [comment]
This is a great idea @paulthebaker . I wonder if we should give the user the choice to choose a telescope when initializing the signal. That way, for instance, L-band at GBT, would set up the number of frequency bins, bandwidth and central frequency.

**Comment by paulthebaker** [comment]
I'm thinking about this again:
 * The `Telescope` class has an `observe` method and methods to add gaussian radiometer noise and RFI to a signal during observation.
 * A `Telescope` should be initialized with collecting area, system temperature, central frequency, band width, and other properties of the telescope itself.
 * A `Telescope` instance should contain all of these things as `@properties` with getters but no setters.
 * A `Telescope` instance should contain a method to instantiate an empty `Signal` of the appropriate size as @Hazboun6 suggested.
 * We should provide convenience objects (as class factories?) for GBT and AO (with choice of receiver/backend).  These are subclassed from `Telescope`.

longer term ideas:
 * Telescopes and pulsars have physical locations.  How does pointing affect the data?
   * T<sub>sky</sub> as function of elevation
   * beam size affects noise
   * beam sensitivity and pointing error?
 * include all ITPA telescopes

**Comment by Hazboun6** [comment]
@bshapiroalbert Can we close this?

**Comment by bshapiroalbert** [comment]
@Hazboun6  I think as it is we can close it. There are probably improvements and clean-ups that need to be done to the telescope class but they are unrelated to this issue.

**Comment by bshapiroalbert** [comment]
I don't think there's a reason to keep this open any more, I'm going to close it.
