### ISSUE TITLE
Input DM is not stored anywhere

### ISSUE THREAD

**Issue by bshapiroalbert** [PsrSigSim/VersionZeroPointZero#115]
As far as I can tell, the input DM that the `ism` class uses to disperse the signal is not actually stored anywhere, in the `ism` class, the `signal`, or the `puslar` unless I missed something. This is probably bad. Also, we should add a `dedisperse()` function to the ism class as well I think once the DM is stored.

**Comment by Hazboun6** [comment]
Added by merging PR #116
