### ISSUE TITLE
using `astropy.units` to handle physical units

### ISSUE THREAD

**Issue by paulthebaker** [PsrSigSim/VersionZeroPointZero#13]
While working on `PSS_utils.py` (PR #12) and `telescope.py` (issue #1, PR #11), I'm noticing some of the utils have specific unit conventions.  This leads to hardcoded unit conversions (i.e `top_hat_width()`) and implicitly requires the user to remember which params should be in MHz v. GHz, etc.

`PINT` gets around this by using `astropy.units`.  I think we should do the same.  For example in [`TOA.__init__()`](https://github.com/nanograv/PINT/blob/master/pint/toa.py#L289), kwarg `freq` accepts either a float assuming MHz or an `astropy.units.Quantity()` object (or I guess any object with compatible units).

```python
import astropy.units as u
...
def __init__(self, ..., freq, ...):
    ...
    if hasattr(freq,'unit'):
        try:
            junk = freq.to(u.MHz)
        except u.UnitConversionError:
            log.error("Frequency for TOA with incompatible unit {0}".format(freq))
        self.freq = freq
    else:
        self.freq = freq * u.MHz
    ...
```
The final `else` sets `self.freq` from the input float in MHz, promoting it to a `Quantity` with units.

This sort of thing seems cumbersome, but I'm starting to think it's the right way to do things in the long run.  Especially as `astropy` becomes more and more the standard.

**Comment by Hazboun6** [comment]
I think we should definitely talk about this. I'll put it on the agenda for the meeting. While I agree that it is a really good idea, I think the question is where does it fall in the priority list?

**Comment by Hazboun6** [comment]
Coming back to this discussion... I was just thinking about starting to implement a few of these changes. Do we need this type of `hasattr()` clause for every unitful parameter? We could easily write a utility script for this...
