### ISSUE TITLE
Unit test and physical tests

### ISSUE THREAD

**Issue by Hazboun6** [PsrSigSim/VersionZeroPointZero#15]
I think the time has come for us to set up some unit test and possible physical tests.  Does anyone have experience with unit tests? Or can they recommend one of the services like Travis?

Can we set up physical test as unit tests?

**Comment by paulthebaker** [comment]
This is going to be a big undertaking.  I started a project for it.  I think that will help us organize a todo list.

**Comment by paulthebaker** [comment]
Travis CI is only free for public repos.  We'll need to take this public if we want to use the same testing and continuous integration system as [PINT](https://github.com/nanograv/PINT) and [enterprise](https://github.com/nanograv/enterprise).

We can either make this repo public and start restructuring for Travis or start a new repo under the [nanograv](https://github.com/nanograv/) organization and put in an "empty" Travis setup.  Then we can copy the code into the appropriate directories there.

@nanograv-pire what do you think?

**Comment by Hazboun6** [comment]
@paulthebaker, What were the problems that Justin was having with Travis concerning Enterprise? Do we know that is the best option?

I like the idea of making a "new" repo that we can port this development version of the simulator into.

**Comment by bshapiroalbert** [comment]
We now have testing through Travis and what I think is extremely good unit testing coverage so I'm going to close this now.
