### ISSUE TITLE
Test failures and large amount of warnings on python3.8.0

### ISSUE THREAD

**Issue by JBorrow** [PsrSigSim/VersionZeroPointZero#157]
I'm getting a few test failures and a lot of warnings on my install of python3.8.0, on MacOS. I have attached the output - can you please tell me what I'm doing wrong?

This is in a fresh virtual environment, and I did:

```
pip install psrsigsim
pip install -r requirements.txt
pip install -r requirements_dev.txt
```

before

```
python3 -m pytest tests
```

The failures are mainly in test_io.py.

I would also like to see the warnings in the tests, particularly the DeprecationWarnings, addressed.

[test_output.txt](https://github.com/PsrSigSim/PsrSigSim/files/5396446/test_output.txt)

This issue is part of my JOSS review.

**Comment by JBorrow** [comment]
It appears that the test failures are connected to astropy `4.0.0` somehow ending up installed on my machine, despite me specifying 3.3.2. However, the tests still generate a large number of warnings.

**Comment by Hazboun6** [comment]
Moving some comments over here, as they seem more appropriate to this issue...

I think that allowing `Python 3.8` shouldn't be an issue (in theory). So I'll add it to the `Travis` configuration `Yaml`. At least then we'll know where issues might arise.

**Comment by Hazboun6** [comment]
Closing this after consulting with @bshapiroalbert .
