### ISSUE TITLE
Make `disperse()` method more efficient

### ISSUE THREAD

**Issue by Hazboun6** [PsrSigSim/VersionZeroPointZero#17]
The `disperse()` method is a constituent of the `ISM()` class. It takes either a baseband signal or a filter bank signal and disperses that signal. The DSP methods used on the different signal types are slightly different, but both involve taking the DFT of the signal. It becomes cumbersome, when the signal reaches a certain length, to do a DFT on the entire signal length. In the `make_pulses` method of the `Pulsar()` class we chunk the data and work with smaller subsets of the data. How can we do something similar for the `disperse()` method? Should we combine the effort in simulate mode, when we are making much longer signals?

**Comment by Hazboun6** [comment]
@bshapiroalbert Do you feel like the `disperse()` method is still a bottle neck? This Issue is really for the old API, but before I delete it I just wanted to see if there is still an issue.

**Comment by bshapiroalbert** [comment]
@Hazboun6 I don't think this is an issue any more, the dispersion is rather fast now (at least in all the ways I've used it), and has the appropriate version of numpy and scipy so I say close it.

**Comment by bshapiroalbert** [comment]
Going to close this issue now since it no longer seems to be a problem, at least in all use cases tested so far.
