### ISSUE TITLE
Free Travis CI is going away

### ISSUE THREAD

**Issue by bshapiroalbert** [PsrSigSim/VersionZeroPointZero#177]
Copying this issue from the PINT page (https://github.com/nanograv/PINT/issues/817), reposted here:

There is a nice discussion of this on the astropy-dev list: https://groups.google.com/g/astropy-dev/c/45frnTEAX-U

Astropy switched from Travis CI to github's "Actions" for CI.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by Hazboun6** [comment]
Here is a decent [tutorial](https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions).

**Comment by bshapiroalbert** [comment]
Awesome! Sorry I have not had time to do this yet. It is on my to-do list still though.

**Comment by Hazboun6** [comment]
It doesn't look like the `Pint` [folks](https://github.com/nanograv/PINT/pull/882) have successfully figured this out yet either. But there are some nice resources in their conversation.

**Comment by bshapiroalbert** [comment]
This was merged into the `joss-reveiw` branch in PR #182 and has been confirmed to run successfully in PRs #183, #180 , and #184 . This still needs to be merged with the main branch but for all intents and purposes this has been completed.
