### ISSUE TITLE
Further paper edits

### ISSUE THREAD

**Issue by arjunsavel** [PsrSigSim/VersionZeroPointZero#190]
The JOSS paper is shaping up nicely! Just a couple more minor comments:

- [x] The multiple parenthetical citations ([@hotan2004, @VanStraten2012], [@Luo2020, @tempo2]) aren't being rendered correctly; I believe the individual citations should be separated by semicolons instead of commas.
- [x] Bell-Burnell  —> Bell Burnell
- [x] Numpy —> NumPy
- [x] Comma after Astropy citation
- [x] general purpose —> general-purpose 

This issue is part of my JOSS review.

**Comment by Hazboun6** [comment]
@arjunsavel I've made all of the changes above to the paper. Thanks for the careful copy editing!
