### ISSUE TITLE
Reference to number of polarizations in `radiometer_noise()`

### ISSUE THREAD

**Issue by Hazboun6** [PsrSigSim/VersionZeroPointZero#28]
#11 @paulthebaker , in the line of code defining `sigS`, `np` is referenced (Numpy) instead of `Np`, but the bigger problem is that `Np`  isn't defined until the `if`, `then` statements just below. 

Maybe we can make `sigS` a method, or parameter, like `Smax`?

**Comment by paulthebaker** [comment]
This was fixed in PR #29.
