### ISSUE TITLE
Documentation for nested methods

### ISSUE THREAD

**Issue by Hazboun6** [PsrSigSim/VersionZeroPointZero#5]
I've added in a file of plotting functions, `PSS_plot.py`, that I've been populating with common pots the user might want as they play with the signal. I've added the methods to the `Signal` class so that all ones needs to do is call the plot type and the function uses the dictionary to build a nice looking plot with the correct parameters. However, the normal docstring that appears, and more importantly the nice help one gets when in a jupyter noteboook (`shift`+`tab`, where the full signature appears with all of the needed variables) does not appear. The command sitting in `signal.py` appears instead. Since these plotting functions have a number of options it would be nice for this to appear. Any thoughts?

**Comment by bshapiroalbert** [comment]
@Hazboun6 is this still relevant or should we close it?

**Comment by Hazboun6** [comment]
It's sort of relevant, but maybe should have been a question posed to StackExchange rather than as an issue? I think we can get around this by making the plotting scripts be classes rather than methods, so that the docstrings will just get inherited. I will close the issue.
