### ISSUE TITLE
Tests for io module

### ISSUE THREAD

**Issue by bshapiroalbert** [PsrSigSim/VersionZeroPointZero#65]
Need to write unit tests for the `io` module in the new API.

**Comment by bshapiroalbert** [comment]
Have added a some basic tests including a test of the `save` function.

**Comment by Hazboun6** [comment]
@bshapiroalbert What is the status here? Are there enough tests currently? I think that for the sake of the API project you can at least move this to in progress, but probably complete for now? Looks like  `io/psrfits.py` could stand a few more tests. It is currently at `67%`.

**Comment by bshapiroalbert** [comment]
@Hazboun6, this probably needs a few more tests, especially to hit all of the if statements. I will add this to my to-do and work on adding a few more tests.

**Comment by bshapiroalbert** [comment]
The `io` class now has substantial unit testing so I am going to close this issue.
