### ISSUE TITLE
Add pyFFTW Capability

### ISSUE THREAD

**Issue by Hazboun6** [PsrSigSim/VersionZeroPointZero#7]
Use the `pyFFTW` package where possible to speed up the discrete fourier transforms that we use in the simulator. Try and make the use optional, possibly by monkey-patching numpy methods.

**Comment by paulthebaker** [comment]
I can take a look at this.  It should be pretty straight forward, something like:

```python
import numpy as np
try:
    import pyfftw
    fft = pyfftw.interfaces.numpy_fft
except:
    fft = np.fft
```

We'll probably want some other `try` statements to use `pyfftw`'s planning and caching (and maybe initializations) to maximize speedups.

I think it's possible to set `scipy.fftpack` so `scipy.signal.fftconvolve` will use `pyfftw` too.

**Comment by Hazboun6** [comment]
Yeah, I agree. I actually already implemented some of this in `scintillation.py` where I needed to take the 2d FFT of Kernel Diffraction Integrals. There I gave the user a choice, but I think that it would be better to just do what you propose here. If they have pyFFTW it is faster, so why not use it. 

I think that this would be especially useful in the `PSS_utils.py` methods.

**Comment by Hazboun6** [comment]
@paulthebaker, I know that at some point you did some testing of these methods. If I recall, the outcome was that for the 1D FFTs that we needed it wasn't that much faster. Is that correct?

**Comment by bshapiroalbert** [comment]
@Hazboun6, @paulthebaker  is this issue to relevant and/or does it need to be addressed?

**Comment by Hazboun6** [comment]
From what I remember @paulthebaker 's tests showed that `pyfftw` did little to improve the speed of most functions for jobs that would be run on a laptop. I think the fold mode we are using for the various simulations that @bshapiroalbert has done for his paper are showing that, at least for now, we can kick the can of higher computation speeds down the road a bit. I'll close this issue, and assume we can easily open a more generic one for speed ups later.
